/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import controlador.ControladorCompras;
import controlador.ControladorOrdenesCompra;
import java.awt.Cursor;
import java.net.URL;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import modelo.Proveedores;
import modelo.Estados;

/**
 *
 * @author User
 */
public class fCompras extends javax.swing.JFrame {

    /**
     * Creates new form Compras
     */
    
    int subTotal;
    
    
    public fCompras() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        fCompras = new javax.swing.JTabbedPane();
        OrdenC = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grArticulosSolic = new javax.swing.JTable();
        btnGenOrden = new javax.swing.JButton();
        cbProveOrden = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnAgrArtiOrden = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        grOrdenes = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        grArticulosStock = new javax.swing.JTable();
        btnEliminaArtiOrden = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        cbBusqEstadoOrden = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        grDetalleOrden = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnAnularOrden = new javax.swing.JButton();
        txtIdProve = new javax.swing.JTextField();
        txtIdOrden = new javax.swing.JTextField();
        btnArticulos = new javax.swing.JButton();
        numCantArtiOrden = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        RegFactura = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnAgrArticuloFact = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        grDetalleArtiFact = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        grDetalleFact = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtOrdenBusqRegFact = new javax.swing.JTextField();
        lblProveedor = new javax.swing.JLabel();
        btnBusqOrdenFact = new javax.swing.JButton();
        txtSubTotal = new javax.swing.JTextField();
        txtIVA = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnGrabFactura = new javax.swing.JButton();
        txtNumFact = new javax.swing.JTextField();
        pickFechaFactura = new com.michaelbaranov.microba.calendar.DatePicker();
        jLabel19 = new javax.swing.JLabel();
        pickVencimiento = new com.michaelbaranov.microba.calendar.DatePicker();
        numCantidadArtFact = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnDevArtiFact = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtPrecioArt = new javax.swing.JTextField();
        btnLimpiarFact = new javax.swing.JButton();
        historicoFacturas = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        grFacturas = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        grDetFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbBusqMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbBusqYear = new javax.swing.JComboBox<>();
        btnBusqHistoricoFact = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modulo de control de Ordenes de Compra y Facturas");

        grArticulosSolic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_articulo", "Nombre", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grArticulosSolic.setColumnSelectionAllowed(true);
        grArticulosSolic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grArticulosSolicMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(grArticulosSolic);
        grArticulosSolic.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (grArticulosSolic.getColumnModel().getColumnCount() > 0) {
            grArticulosSolic.getColumnModel().getColumn(0).setMinWidth(0);
            grArticulosSolic.getColumnModel().getColumn(0).setPreferredWidth(0);
            grArticulosSolic.getColumnModel().getColumn(0).setMaxWidth(0);
            grArticulosSolic.getColumnModel().getColumn(2).setMinWidth(70);
            grArticulosSolic.getColumnModel().getColumn(2).setPreferredWidth(70);
            grArticulosSolic.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        btnGenOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salvar.png"))); // NOI18N
        btnGenOrden.setText("Generar Orden");
        btnGenOrden.setEnabled(false);
        btnGenOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenOrdenActionPerformed(evt);
            }
        });

        cbProveOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProveOrdenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Proveedor:");

        btnAgrArtiOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Actions-go-next-icon.png"))); // NOI18N
        btnAgrArtiOrden.setEnabled(false);
        btnAgrArtiOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrArtiOrdenActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Generar Orden de Compra");
        jLabel9.setMinimumSize(new java.awt.Dimension(105, 14));

        grOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Orden", "Proveedor", "Fecha de Solicitud", "Estado", "id_estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grOrdenesMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(grOrdenes);
        if (grOrdenes.getColumnModel().getColumnCount() > 0) {
            grOrdenes.getColumnModel().getColumn(0).setMinWidth(60);
            grOrdenes.getColumnModel().getColumn(0).setPreferredWidth(60);
            grOrdenes.getColumnModel().getColumn(0).setMaxWidth(60);
            grOrdenes.getColumnModel().getColumn(2).setMinWidth(110);
            grOrdenes.getColumnModel().getColumn(2).setPreferredWidth(110);
            grOrdenes.getColumnModel().getColumn(2).setMaxWidth(110);
            grOrdenes.getColumnModel().getColumn(3).setMinWidth(100);
            grOrdenes.getColumnModel().getColumn(3).setPreferredWidth(100);
            grOrdenes.getColumnModel().getColumn(3).setMaxWidth(100);
            grOrdenes.getColumnModel().getColumn(4).setMinWidth(0);
            grOrdenes.getColumnModel().getColumn(4).setPreferredWidth(0);
            grOrdenes.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        grArticulosStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_articulo", "Nombre", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grArticulosStock.setColumnSelectionAllowed(true);
        grArticulosStock.setFocusable(false);
        grArticulosStock.getTableHeader().setReorderingAllowed(false);
        grArticulosStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grArticulosStockMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(grArticulosStock);
        grArticulosStock.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (grArticulosStock.getColumnModel().getColumnCount() > 0) {
            grArticulosStock.getColumnModel().getColumn(0).setMinWidth(0);
            grArticulosStock.getColumnModel().getColumn(0).setPreferredWidth(0);
            grArticulosStock.getColumnModel().getColumn(0).setMaxWidth(0);
            grArticulosStock.getColumnModel().getColumn(2).setMinWidth(60);
            grArticulosStock.getColumnModel().getColumn(2).setPreferredWidth(60);
            grArticulosStock.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        btnEliminaArtiOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Actions-edit-delete-icon.png"))); // NOI18N
        btnEliminaArtiOrden.setEnabled(false);
        btnEliminaArtiOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaArtiOrdenActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Articulos");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Articulos a Solicitar");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Busqueda por Estado:");

        grDetalleOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_art", "Articulo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grDetalleOrden.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(grDetalleOrden);
        grDetalleOrden.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (grDetalleOrden.getColumnModel().getColumnCount() > 0) {
            grDetalleOrden.getColumnModel().getColumn(0).setMinWidth(0);
            grDetalleOrden.getColumnModel().getColumn(0).setPreferredWidth(0);
            grDetalleOrden.getColumnModel().getColumn(0).setMaxWidth(0);
            grDetalleOrden.getColumnModel().getColumn(2).setMinWidth(70);
            grDetalleOrden.getColumnModel().getColumn(2).setPreferredWidth(70);
            grDetalleOrden.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Consultar Ordenes de Compra");
        jLabel10.setMinimumSize(new java.awt.Dimension(105, 14));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("Detalle");

        btnAnularOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/clean-ico.png"))); // NOI18N
        btnAnularOrden.setText("Anular Orden");
        btnAnularOrden.setEnabled(false);
        btnAnularOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularOrdenActionPerformed(evt);
            }
        });

        txtIdProve.setEditable(false);

        btnArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search-icon.png"))); // NOI18N

        jLabel23.setText("Cantidad");

        javax.swing.GroupLayout OrdenCLayout = new javax.swing.GroupLayout(OrdenC);
        OrdenC.setLayout(OrdenCLayout);
        OrdenCLayout.setHorizontalGroup(
            OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdenCLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdenCLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtIdProve, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbProveOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(btnGenOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(OrdenCLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(OrdenCLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAnularOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(txtIdOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator2)
                    .addGroup(OrdenCLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrdenCLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdenCLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(40, 40, 40))
                                    .addGroup(OrdenCLayout.createSequentialGroup()
                                        .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgrArtiOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEliminaArtiOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                            .addGroup(OrdenCLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(numCantArtiOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(OrdenCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(OrdenCLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE))
                            .addGroup(OrdenCLayout.createSequentialGroup()
                                .addComponent(cbBusqEstadoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))))
                    .addGroup(OrdenCLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        OrdenCLayout.setVerticalGroup(
            OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdenCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnArticulos, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdenCLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrdenCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numCantArtiOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgrArtiOrden)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminaArtiOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrdenCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbProveOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbBusqEstadoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(OrdenCLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OrdenCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnularOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        fCompras.addTab("Ordenes de Compras", OrdenC);

        RegFactura.setFocusable(false);

        jLabel6.setText("N° Orden de Compra");

        btnAgrArticuloFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Actions-go-next-icon.png"))); // NOI18N
        btnAgrArticuloFact.setEnabled(false);
        btnAgrArticuloFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrArticuloFactActionPerformed(evt);
            }
        });

        grDetalleArtiFact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_art", "Articulo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grDetalleArtiFact.setFocusable(false);
        grDetalleArtiFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grDetalleArtiFactMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(grDetalleArtiFact);
        grDetalleArtiFact.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (grDetalleArtiFact.getColumnModel().getColumnCount() > 0) {
            grDetalleArtiFact.getColumnModel().getColumn(0).setMinWidth(0);
            grDetalleArtiFact.getColumnModel().getColumn(0).setPreferredWidth(0);
            grDetalleArtiFact.getColumnModel().getColumn(0).setMaxWidth(0);
            grDetalleArtiFact.getColumnModel().getColumn(2).setMinWidth(60);
            grDetalleArtiFact.getColumnModel().getColumn(2).setPreferredWidth(60);
            grDetalleArtiFact.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        grDetalleFact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_art", "Articulo", "Cantidad", "Precio Unitario", "Vencimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grDetalleFact.setColumnSelectionAllowed(true);
        grDetalleFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grDetalleFactMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(grDetalleFact);
        grDetalleFact.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (grDetalleFact.getColumnModel().getColumnCount() > 0) {
            grDetalleFact.getColumnModel().getColumn(0).setMinWidth(0);
            grDetalleFact.getColumnModel().getColumn(0).setPreferredWidth(0);
            grDetalleFact.getColumnModel().getColumn(0).setMaxWidth(0);
            grDetalleFact.getColumnModel().getColumn(2).setMinWidth(60);
            grDetalleFact.getColumnModel().getColumn(2).setPreferredWidth(60);
            grDetalleFact.getColumnModel().getColumn(2).setMaxWidth(60);
            grDetalleFact.getColumnModel().getColumn(3).setMinWidth(100);
            grDetalleFact.getColumnModel().getColumn(3).setPreferredWidth(100);
            grDetalleFact.getColumnModel().getColumn(3).setMaxWidth(100);
            grDetalleFact.getColumnModel().getColumn(4).setMinWidth(100);
            grDetalleFact.getColumnModel().getColumn(4).setPreferredWidth(100);
            grDetalleFact.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jLabel7.setText("N° de Factura:");

        jLabel8.setText("IVA (19%):");

        jLabel11.setText("Sub- TOTAL:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("TOTAL:");

        jLabel17.setText("Fecha:");

        jLabel18.setText("Proveedor:");

        lblProveedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(102, 204, 0));

        btnBusqOrdenFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search-icon.png"))); // NOI18N

        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubTotal.setFocusable(false);

        txtIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIVA.setFocusable(false);

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(51, 204, 0));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setFocusable(false);

        btnGrabFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGrabFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salvar.png"))); // NOI18N
        btnGrabFactura.setText("Procesar Factura");

        try {
            pickFechaFactura.setDate(null);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        pickFechaFactura.setDateFormat(new SimpleDateFormat ("dd-MM-yyyy"));
        pickFechaFactura.setMinimumSize(new java.awt.Dimension(132, 25));
        pickFechaFactura.setPreferredSize(new java.awt.Dimension(122, 25));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Registro de Facturas (Compras)");
        jLabel19.setMinimumSize(new java.awt.Dimension(105, 14));

        try {
            pickVencimiento.setDate(null);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        pickVencimiento.setMinimumSize(new java.awt.Dimension(122, 22));
        pickVencimiento.setPreferredSize(new java.awt.Dimension(122, 30));

        jLabel4.setText("Cantidad");

        jLabel21.setText("Vencimiento");

        btnDevArtiFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Actions-edit-delete-icon.png"))); // NOI18N
        btnDevArtiFact.setEnabled(false);
        btnDevArtiFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevArtiFactActionPerformed(evt);
            }
        });

        jLabel22.setText("Precio Unitario");

        btnLimpiarFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/clean-ico.png"))); // NOI18N

        javax.swing.GroupLayout RegFacturaLayout = new javax.swing.GroupLayout(RegFactura);
        RegFactura.setLayout(RegFacturaLayout);
        RegFacturaLayout.setHorizontalGroup(
            RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegFacturaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegFacturaLayout.createSequentialGroup()
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegFacturaLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(325, 325, 325))
                            .addGroup(RegFacturaLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegFacturaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtOrdenBusqRegFact, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBusqOrdenFact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarFact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumFact, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174))
                    .addGroup(RegFacturaLayout.createSequentialGroup()
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RegFacturaLayout.createSequentialGroup()
                                    .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(3, 3, 3)
                                    .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIVA)
                                            .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(RegFacturaLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(RegFacturaLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(numCantidadArtFact, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegFacturaLayout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(RegFacturaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pickVencimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegFacturaLayout.createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtPrecioArt, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnAgrArticuloFact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                    .addComponent(btnDevArtiFact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
            .addGroup(RegFacturaLayout.createSequentialGroup()
                .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegFacturaLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegFacturaLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(btnGrabFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegFacturaLayout.setVerticalGroup(
            RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegFacturaLayout.createSequentialGroup()
                .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegFacturaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBusqOrdenFact)
                            .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtOrdenBusqRegFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(btnLimpiarFact))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(401, 401, 401))
                    .addGroup(RegFacturaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RegFacturaLayout.createSequentialGroup()
                                .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pickFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(RegFacturaLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numCantidadArtFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pickVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrecioArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAgrArticuloFact, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDevArtiFact, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnGrabFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        fCompras.addTab("Registro de Facturas", RegFactura);

        grFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° de orden", "Proveedor", "Factura N°", "Fecha Solicitud", "Fecha Facturación", "Total", "id_oc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grFacturas.setFocusable(false);
        grFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grFacturasMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(grFacturas);
        if (grFacturas.getColumnModel().getColumnCount() > 0) {
            grFacturas.getColumnModel().getColumn(0).setMinWidth(80);
            grFacturas.getColumnModel().getColumn(0).setPreferredWidth(80);
            grFacturas.getColumnModel().getColumn(0).setMaxWidth(80);
            grFacturas.getColumnModel().getColumn(2).setMinWidth(85);
            grFacturas.getColumnModel().getColumn(2).setPreferredWidth(85);
            grFacturas.getColumnModel().getColumn(2).setMaxWidth(85);
            grFacturas.getColumnModel().getColumn(3).setMinWidth(100);
            grFacturas.getColumnModel().getColumn(3).setPreferredWidth(100);
            grFacturas.getColumnModel().getColumn(3).setMaxWidth(100);
            grFacturas.getColumnModel().getColumn(4).setMinWidth(120);
            grFacturas.getColumnModel().getColumn(4).setPreferredWidth(120);
            grFacturas.getColumnModel().getColumn(4).setMaxWidth(120);
            grFacturas.getColumnModel().getColumn(5).setMinWidth(85);
            grFacturas.getColumnModel().getColumn(5).setPreferredWidth(85);
            grFacturas.getColumnModel().getColumn(5).setMaxWidth(85);
            grFacturas.getColumnModel().getColumn(6).setMinWidth(0);
            grFacturas.getColumnModel().getColumn(6).setPreferredWidth(0);
            grFacturas.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        grDetFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Articulo", "Cantidad", "Precio Unitario", "Vencimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grDetFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grDetFacturaMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(grDetFactura);
        if (grDetFactura.getColumnModel().getColumnCount() > 0) {
            grDetFactura.getColumnModel().getColumn(1).setMinWidth(80);
            grDetFactura.getColumnModel().getColumn(1).setPreferredWidth(80);
            grDetFactura.getColumnModel().getColumn(1).setMaxWidth(80);
            grDetFactura.getColumnModel().getColumn(2).setMinWidth(110);
            grDetFactura.getColumnModel().getColumn(2).setPreferredWidth(110);
            grDetFactura.getColumnModel().getColumn(2).setMaxWidth(110);
            grDetFactura.getColumnModel().getColumn(3).setMinWidth(80);
            grDetFactura.getColumnModel().getColumn(3).setPreferredWidth(80);
            grDetFactura.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel1.setText("DETALLE DE FACTURA");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Consulta de Historico de Facturas (Compras)");
        jLabel20.setMinimumSize(new java.awt.Dimension(105, 14));

        cbBusqMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel2.setText("Busqueda por  Mes:");

        jLabel3.setText("Año:");

        cbBusqYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        btnBusqHistoricoFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/binoculars-icon.png"))); // NOI18N

        javax.swing.GroupLayout historicoFacturasLayout = new javax.swing.GroupLayout(historicoFacturas);
        historicoFacturas.setLayout(historicoFacturasLayout);
        historicoFacturasLayout.setHorizontalGroup(
            historicoFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historicoFacturasLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBusqMes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBusqYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBusqHistoricoFact, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historicoFacturasLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(historicoFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historicoFacturasLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historicoFacturasLayout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historicoFacturasLayout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historicoFacturasLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(393, 393, 393))))
        );
        historicoFacturasLayout.setVerticalGroup(
            historicoFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historicoFacturasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(historicoFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBusqMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cbBusqYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusqHistoricoFact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fCompras.addTab("Historico de Facturas", historicoFacturas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fCompras)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fCompras))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAnularOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnularOrdenActionPerformed

    private void cbProveOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProveOrdenActionPerformed
        int idProve =this.cbProveOrden.getItemAt(this.cbProveOrden.getSelectedIndex()).getId_proveedor();
        this.txtIdProve.setText(String.valueOf(idProve));
    }//GEN-LAST:event_cbProveOrdenActionPerformed

    private void btnGenOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenOrdenActionPerformed
        this.grArticulosStock.clearSelection();
        this.btnEliminaArtiOrden.setEnabled(false);
    }//GEN-LAST:event_btnGenOrdenActionPerformed

    private void btnAgrArtiOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrArtiOrdenActionPerformed
        int fila = this.grArticulosStock.getSelectedRow();
        DefaultTableModel datosFilaStock = (DefaultTableModel) this.grArticulosStock.getModel();
        DefaultTableModel datosFilaArtiOrden = (DefaultTableModel) this.grArticulosSolic.getModel();
        Object[] object = new Object[3];
        object[0] = datosFilaStock.getValueAt(fila, 0).toString();
        object[1] = datosFilaStock.getValueAt(fila, 1).toString();
        object[2] = this.numCantArtiOrden.getValue().toString();
        datosFilaArtiOrden.addRow(object);
        this.grArticulosStock.clearSelection();
        this.btnAgrArtiOrden.setEnabled(false);
        this.btnGenOrden.setEnabled(true);
    }//GEN-LAST:event_btnAgrArtiOrdenActionPerformed

    private void btnEliminaArtiOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaArtiOrdenActionPerformed
        DefaultTableModel datosFilaArtiOrden = (DefaultTableModel) this.grArticulosSolic.getModel();
        datosFilaArtiOrden.removeRow(this.grArticulosSolic.getSelectedRow());
        this.btnEliminaArtiOrden.setEnabled(false);
    }//GEN-LAST:event_btnEliminaArtiOrdenActionPerformed

    private void grArticulosSolicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grArticulosSolicMouseClicked
        this.btnEliminaArtiOrden.setEnabled(true);
    }//GEN-LAST:event_grArticulosSolicMouseClicked

    private void grArticulosStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grArticulosStockMouseClicked
        this.btnAgrArtiOrden.setEnabled(true);
    }//GEN-LAST:event_grArticulosStockMouseClicked

    private void grOrdenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grOrdenesMouseClicked
        int fila = this.grOrdenes.getSelectedRow();
        DefaultTableModel ordenesCompraModel = (DefaultTableModel) this.grOrdenes.getModel();
        this.txtIdOrden.setText(ordenesCompraModel.getValueAt(fila, 0).toString());
        Integer Estado = Integer.parseInt(ordenesCompraModel.getValueAt(fila, 4).toString());

        if (Estado == 1) {
            this.btnAnularOrden.setEnabled(true);
        } else {
            this.btnAnularOrden.setEnabled(false);
        }

        try {
            ControladorOrdenesCompra co = new ControladorOrdenesCompra(this);
            co.listarDetalleOrden(this.grDetalleOrden, Integer.parseInt(this.txtIdOrden.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(fMaestros.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_grOrdenesMouseClicked

    private void btnAgrArticuloFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrArticuloFactActionPerformed
        SimpleDateFormat fecha = new SimpleDateFormat("dd-MM-yyyy");
        int fila = this.grDetalleArtiFact.getSelectedRow();

        DefaultTableModel datosFilaArtiFact = (DefaultTableModel) this.grDetalleArtiFact.getModel();
        DefaultTableModel datosFilaDetalleFact = (DefaultTableModel) this.grDetalleFact.getModel();
        
        Object[] object = new Object[5];
        object[0] = datosFilaArtiFact.getValueAt(fila, 0).toString();
        object[1] = datosFilaArtiFact.getValueAt(fila, 1).toString();
        object[2] = this.numCantidadArtFact.getValue().toString();
        object[3] = this.txtPrecioArt.getText();
        object[4] = fecha.format(this.pickVencimiento.getDate());

        datosFilaDetalleFact.addRow(object);
                   
        calcularTotal();

    }//GEN-LAST:event_btnAgrArticuloFactActionPerformed

    private void grDetalleArtiFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grDetalleArtiFactMouseClicked
        this.btnAgrArticuloFact.setEnabled(true);
    }//GEN-LAST:event_grDetalleArtiFactMouseClicked

    private void btnDevArtiFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevArtiFactActionPerformed
        DefaultTableModel datosFilaDetalleFact = (DefaultTableModel) this.grDetalleFact.getModel();
        datosFilaDetalleFact.removeRow(this.grDetalleFact.getSelectedRow());
        calcularTotal();
        this.btnDevArtiFact.setEnabled(false);
        
    }//GEN-LAST:event_btnDevArtiFactActionPerformed

    private void grDetalleFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grDetalleFactMouseClicked
        this.btnDevArtiFact.setEnabled(true);
    }//GEN-LAST:event_grDetalleFactMouseClicked

    private void grDetFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grDetFacturaMouseClicked
              
    }//GEN-LAST:event_grDetFacturaMouseClicked

    private void grFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grFacturasMouseClicked
        ControladorCompras cc;
        DefaultTableModel datosFilaFact = (DefaultTableModel) this.grFacturas.getModel();
        try {
            cc = new ControladorCompras(this);
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            cc.listarDetalleFactura(this.grDetFactura, Integer.parseInt(datosFilaFact.getValueAt(this.grFacturas.getSelectedRow(),6).toString()));
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (SQLException ex) {
            Logger.getLogger(fCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_grFacturasMouseClicked

        
    @SuppressWarnings("SuspiciousIndentAfterControlStatement")
    private void calcularTotal() {
        DefaultTableModel datosFilaDetalleFact = (DefaultTableModel) this.grDetalleFact.getModel();
        subTotal = 0;
        
        if(this.grDetalleFact.getRowCount()>0)
        for (int i = 0; i < this.grDetalleFact.getRowCount(); i++) {
            subTotal = subTotal + (Integer.parseInt(datosFilaDetalleFact.getValueAt(i, 3).toString()) * Integer.parseInt(datosFilaDetalleFact.getValueAt(i, 2).toString()));
        }

        this.txtSubTotal.setText(String.valueOf(subTotal));
        this.txtIVA.setText(String.valueOf(Math.round(subTotal * 0.19)));
        this.txtTotal.setText(String.valueOf(Math.round(subTotal * 1.19)));

        this.btnAgrArticuloFact.setEnabled(false);
        this.btnGrabFactura.setEnabled(true);
    }
    
    public static void iniciar() throws SQLException {
        fCompras fc = new fCompras();
        fc.setVisible(true);
        fc.setLocationRelativeTo(null);
        ControladorOrdenesCompra c = new ControladorOrdenesCompra(fc);
        ControladorCompras cc = new ControladorCompras(fc);
        fc.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        c.listarCbProveedores(fc.cbProveOrden);
        c.listarCbEstado(fc.cbBusqEstadoOrden);
        c.listarOrdenes();
        fc.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    
    
    /**
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        iniciar();
        /* Create and display the form */
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OrdenC;
    private javax.swing.JPanel RegFactura;
    private javax.swing.JButton btnAgrArtiOrden;
    public javax.swing.JButton btnAgrArticuloFact;
    public javax.swing.JButton btnAnularOrden;
    public javax.swing.JButton btnArticulos;
    public javax.swing.JButton btnBusqHistoricoFact;
    public javax.swing.JButton btnBusqOrdenFact;
    public javax.swing.JButton btnDevArtiFact;
    private javax.swing.JButton btnEliminaArtiOrden;
    public javax.swing.JButton btnGenOrden;
    public javax.swing.JButton btnGrabFactura;
    public javax.swing.JButton btnLimpiarFact;
    public javax.swing.JComboBox<Estados> cbBusqEstadoOrden;
    public javax.swing.JComboBox<String> cbBusqMes;
    public javax.swing.JComboBox<String> cbBusqYear;
    public javax.swing.JComboBox<modelo.Proveedores> cbProveOrden;
    public javax.swing.JTabbedPane fCompras;
    public javax.swing.JTable grArticulosSolic;
    public javax.swing.JTable grArticulosStock;
    public javax.swing.JTable grDetFactura;
    public javax.swing.JTable grDetalleArtiFact;
    public javax.swing.JTable grDetalleFact;
    public javax.swing.JTable grDetalleOrden;
    public javax.swing.JTable grFacturas;
    public javax.swing.JTable grOrdenes;
    private javax.swing.JPanel historicoFacturas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable9;
    public javax.swing.JLabel lblProveedor;
    private javax.swing.JSpinner numCantArtiOrden;
    public javax.swing.JSpinner numCantidadArtFact;
    public com.michaelbaranov.microba.calendar.DatePicker pickFechaFactura;
    public com.michaelbaranov.microba.calendar.DatePicker pickVencimiento;
    public javax.swing.JTextField txtIVA;
    public javax.swing.JTextField txtIdOrden;
    public javax.swing.JTextField txtIdProve;
    public javax.swing.JTextField txtNumFact;
    public javax.swing.JTextField txtOrdenBusqRegFact;
    public javax.swing.JTextField txtPrecioArt;
    public javax.swing.JTextField txtSubTotal;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
