/**
 * @author Carlos Thieme
 * fecha   13/09/2021
 * 
 */
package vista;
import controlador.ControladorMain;
import java.awt.Cursor;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import modelo.conectDb;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


public class fMain extends javax.swing.JFrame {

    /**
     * Creates new form fMain
     */
    public fMain() {
        URL iconURL = getClass().getResource("/imgs/dgicon.png");        
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        mnuMenuBar = new javax.swing.JMenuBar();
        mnuVentas = new javax.swing.JMenu();
        mnuCompras = new javax.swing.JMenu();
        mnuInformes = new javax.swing.JMenu();
        mnInventario = new javax.swing.JMenuItem();
        mnInventario1 = new javax.swing.JMenuItem();
        mnuArticulosVencer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuPacksReport = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuClientesReport = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuVentasReport = new javax.swing.JMenuItem();
        mnuMaestros = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Background2.png"))); // NOI18N
        lblLogo.setAlignmentX(0.5F);
        lblLogo.setFocusable(false);
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mnuVentas.setForeground(new java.awt.Color(0, 0, 204));
        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ventas-icon.png"))); // NOI18N
        mnuVentas.setText("Ventas");
        mnuVentas.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mnuVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuVentasMouseClicked(evt);
            }
        });
        mnuMenuBar.add(mnuVentas);

        mnuCompras.setForeground(new java.awt.Color(0, 0, 204));
        mnuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/compras-icon.png"))); // NOI18N
        mnuCompras.setText("Compras");
        mnuCompras.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mnuCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuComprasMouseClicked(evt);
            }
        });
        mnuMenuBar.add(mnuCompras);

        mnuInformes.setForeground(new java.awt.Color(0, 0, 204));
        mnuInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/reportes-ico.png"))); // NOI18N
        mnuInformes.setText("Informes");
        mnuInformes.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        mnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/articulos-ico.jpg"))); // NOI18N
        mnInventario.setText("Articulos Ordenados por Mayor Stock");
        mnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInventarioActionPerformed(evt);
            }
        });
        mnuInformes.add(mnInventario);

        mnInventario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/articulos-ico.jpg"))); // NOI18N
        mnInventario1.setText("Articulos Ordenados por Stock Critico");
        mnInventario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInventario1ActionPerformed(evt);
            }
        });
        mnuInformes.add(mnInventario1);

        mnuArticulosVencer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vencimiento-ico.jpg"))); // NOI18N
        mnuArticulosVencer.setText("Articulos por Vencer");
        mnuArticulosVencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArticulosVencerActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuArticulosVencer);
        mnuInformes.add(jSeparator1);

        mnuPacksReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/distribucion-ico.png"))); // NOI18N
        mnuPacksReport.setText("Packs");
        mnuPacksReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPacksReportActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuPacksReport);
        mnuInformes.add(jSeparator2);

        mnuClientesReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/clientes-ico.png"))); // NOI18N
        mnuClientesReport.setText("Clientes");
        mnuClientesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesReportActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuClientesReport);
        mnuInformes.add(jSeparator3);

        mnuVentasReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/regalo-ico.png"))); // NOI18N
        mnuVentasReport.setText("Ventas");
        mnuVentasReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasReportActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuVentasReport);

        mnuMenuBar.add(mnuInformes);

        mnuMaestros.setForeground(new java.awt.Color(0, 0, 204));
        mnuMaestros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/maestros-icon.png"))); // NOI18N
        mnuMaestros.setText("Maestros");
        mnuMaestros.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mnuMaestros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMaestrosMouseClicked(evt);
            }
        });
        mnuMenuBar.add(mnuMaestros);
        mnuMenuBar.add(jMenu1);

        mnuSalir.setForeground(new java.awt.Color(0, 0, 204));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Log-Out-icon.png"))); // NOI18N
        mnuSalir.setText("SALIR");
        mnuSalir.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        mnuMenuBar.add(mnuSalir);

        setJMenuBar(mnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(286, 286, 286))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblLogo)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
    }//GEN-LAST:event_formWindowStateChanged

    private void mnuMaestrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMaestrosMouseClicked
        ControladorMain.btnMaestros();
    }//GEN-LAST:event_mnuMaestrosMouseClicked

    private void mnuVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuVentasMouseClicked
        ControladorMain.btnVentas();
    }//GEN-LAST:event_mnuVentasMouseClicked

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        ControladorMain.btnSalir();
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void mnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInventarioActionPerformed
        genReporte("src\\reportes\\articulosDesc.jasper");
    }//GEN-LAST:event_mnInventarioActionPerformed

    private void mnInventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInventario1ActionPerformed
        genReporte("src\\reportes\\ArticulosAsc.jasper");
    }//GEN-LAST:event_mnInventario1ActionPerformed

    private void mnuArticulosVencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArticulosVencerActionPerformed
        genReporte("src\\reportes\\ArticulosVencer.jasper");
    }//GEN-LAST:event_mnuArticulosVencerActionPerformed

    private void mnuPacksReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPacksReportActionPerformed
        genReporte("src\\reportes\\packs.jasper");
    }//GEN-LAST:event_mnuPacksReportActionPerformed

    private void mnuClientesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesReportActionPerformed
        genReporte("src\\reportes\\Clientes.jasper");
    }//GEN-LAST:event_mnuClientesReportActionPerformed

    private void mnuVentasReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuVentasReportActionPerformed

    private void mnuComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuComprasMouseClicked
       ControladorMain.btnCompras();
    }//GEN-LAST:event_mnuComprasMouseClicked

    private void genReporte(String rep){
        
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            conectDb conn = new conectDb();
            Connection cn = conn.getConexion();
            //JasperReport reporte;
            String path = rep;
            InputStream reporte = JRLoader.getFileInputStream(path);
            //reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            //reporte = JasperCompileManager.compileReport(rep);
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, cn);
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            view.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(fMain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblLogo;
    public javax.swing.JMenuItem mnInventario;
    public javax.swing.JMenuItem mnInventario1;
    public javax.swing.JMenuItem mnuArticulosVencer;
    public javax.swing.JMenuItem mnuClientesReport;
    public javax.swing.JMenu mnuCompras;
    private javax.swing.JMenu mnuInformes;
    private javax.swing.JMenu mnuMaestros;
    private javax.swing.JMenuBar mnuMenuBar;
    public javax.swing.JMenuItem mnuPacksReport;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuVentas;
    public javax.swing.JMenuItem mnuVentasReport;
    // End of variables declaration//GEN-END:variables
}
